print("Naufal daffa ulhaq")
print("Hello World!")
print("Welcome to the Algorithm and Programming Course")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("hallo = 'naufal' ")